"""
Script untuk membuat Excel file dengan database sistem pakar WiFi troubleshooting
"""

import pandas as pd

output_file = r"c:\laragon\www\wifi_troubleshoot\WiFi_Expert_System_Database.xlsx"

# ============================================================================
# SHEET 1: GANGGUAN (DISTURBANCES)
# ============================================================================
gangguan_df = pd.DataFrame(
    {
        "Kode": ["G01", "G02", "G03", "G04", "G05", "G06", "G07", "G08", "G09", "G10"],
        "Nama Gangguan": [
            "Koneksi WiFi Lambat",
            "Putus Koneksi Berulang",
            "Sinyal Lemah",
            "Latensi Tinggi",
            "Masalah Resolusi DNS",
            "Masalah DHCP (IP Assignment)",
            "AP Overheating",
            "Gangguan Interferensi",
            "Kegagalan Autentikasi",
            "Kemacetan Bandwidth",
        ],
        "Deskripsi": [
            "Kecepatan internet WiFi di bawah standar",
            "WiFi terputus dan tersambung kembali berkali-kali",
            "Kekuatan sinyal WiFi sangat rendah di lokasi tertentu",
            "Delay/ping tinggi saat mengakses internet",
            "Tidak bisa akses website atau akses lambat saat DNS lookup",
            "Perangkat tidak mendapat IP atau mendapat IP invalid",
            "Perangkat Access Point panas dan performa menurun",
            "Sinyal WiFi terganggu oleh perangkat elektronik lain",
            "Perangkat tidak bisa login ke WiFi atau password error",
            "Bandwidth penuh, banyak device terhubung, koneksi lambat",
        ],
        "Severity": [
            "medium",
            "high",
            "low",
            "medium",
            "medium",
            "high",
            "high",
            "medium",
            "high",
            "high",
        ],
        "Keterangan": [
            "Sering terjadi, biasanya bisa diatasi dengan optimization",
            "Critical, perlu investigasi segera",
            "Tergantung lokasi, bisa diatasi dengan repositioning AP",
            "Berdampak pada user experience VoIP dan gaming",
            "Bisa diatasi dengan ganti DNS server",
            "Perlu restart DHCP server atau AP",
            "Risk: Hardware damage, perlu penggantian",
            "Bisa diatasi dengan perubahan channel",
            "Security issue, segera verifikasi",
            "Perlu QoS management dan user education",
        ],
    }
)

# ============================================================================
# SHEET 2: PENYEBAB (CAUSES)
# ============================================================================
penyebab_df = pd.DataFrame(
    {
        "Kode": [
            "P01",
            "P02",
            "P03",
            "P04",
            "P05",
            "P06",
            "P07",
            "P08",
            "P09",
            "P10",
            "P11",
            "P12",
            "P13",
            "P14",
            "P15",
            "P16",
            "P17",
            "P18",
            "P19",
            "P20",
            "P21",
            "P22",
            "P23",
        ],
        "Penyebab": [
            "Jarak jauh dari AP",
            "Antena AP rusak atau tidak optimal",
            "Channel WiFi tidak optimal/penuh",
            "Bandwidth settings tidak sesuai",
            "Daya transmit AP terlalu rendah",
            "Kabel Ethernet rusak atau lepas",
            "Router/AP mengalami overheating",
            "Firmware AP tidak up-to-date",
            "Interferensi dari perangkat 2.4GHz lain",
            "ISP/Provider koneksi internet bermasalah",
            "Jumlah user terlalu banyak (> 30 devices)",
            "DNS Server tidak responsif",
            "DHCP Server sedang bermasalah",
            "IP Address range penuh/habis",
            "Perangkat klien mengalami hardware/driver problem",
            "MAC filtering aktif dan device MAC tidak terdaftar/terblokir",
            "Password WiFi salah, belum disimpan, atau kedaluwarsa",
            "Kapasitas memori AP penuh/RAM terbatas",
            "WPS aktif dan ada autentikasi issue",
            "Thermal throttling pada AP",
            "MAC spoofing atau MAC address collision terjadi",
            "WPA2/WPA3 encryption mismatch antara AP dan device",
            "SSID tersembunyi (hidden network) atau broadcast setting tidak sesuai",
        ],
        "Jenis": [
            "hardware",
            "hardware",
            "configuration",
            "configuration",
            "configuration",
            "hardware",
            "hardware",
            "software",
            "environmental",
            "external",
            "load",
            "service",
            "service",
            "configuration",
            "client",
            "security",
            "security",
            "hardware",
            "security",
            "hardware",
            "security",
            "security",
            "configuration",
        ],
        "CF Min": [
            0.6,
            0.7,
            0.5,
            0.4,
            0.6,
            0.8,
            0.7,
            0.5,
            0.6,
            0.75,
            0.6,
            0.65,
            0.7,
            0.65,
            0.5,
            0.8,
            0.75,
            0.6,
            0.4,
            0.7,
            0.65,
            0.7,
            0.6,
        ],
        "CF Max": [
            0.8,
            0.9,
            0.7,
            0.6,
            0.8,
            0.95,
            0.9,
            0.7,
            0.8,
            0.95,
            0.85,
            0.85,
            0.9,
            0.85,
            0.75,
            0.95,
            0.95,
            0.8,
            0.6,
            0.9,
            0.85,
            0.9,
            0.8,
        ],
        "Solusi": [
            "Pindahkan AP lebih dekat atau tambah AP",
            "Ganti antena AP",
            "Cek dan ubah WiFi channel",
            "Optimalkan setting bandwidth 20MHz/40MHz",
            "Tingkatkan TX power di AP settings",
            "Periksa dan perbaiki kabel Ethernet",
            "Bersihkan AP, pastikan ventilasi baik",
            "Update firmware AP ke versi terbaru",
            "Ubah WiFi channel ke frekuensi yang lebih sepi",
            "Hubungi ISP, check ISP status",
            "Limit koneksi per device, implementasi QoS",
            "Ganti DNS server (8.8.8.8 atau 1.1.1.1)",
            "Restart DHCP service atau AP",
            "Extend IP range atau optimize IP allocation",
            "Update driver network card klien",
            "Register MAC address device atau disable MAC filter",
            "Verifikasi password WiFi dan pastikan input benar",
            "Restart AP untuk clear memory",
            "Disable WPS jika tidak diperlukan",
            "Kurangi beban AP atau tingkatkan ventilasi",
            "Periksa MAC uniqueness, disable MAC spoofing jika ada",
            "Sesuaikan encryption standard di AP atau device",
            "Enable SSID broadcast atau input SSID hidden secara manual",
        ],
    }
)

# ============================================================================
# SHEET 3: RULES
# ============================================================================
rules_df = pd.DataFrame(
    {
        "Rule ID": [
            "R001",
            "R002",
            "R003",
            "R004",
            "R005",
            "R006",
            "R007",
            "R008",
            "R009",
            "R010",
            "R011",
            "R012",
            "R013",
            "R014",
            "R015",
            "R016",
            "R017",
            "R018",
            "R019",
            "R020",
            "R021",
            "R022",
            "R023",
            "R024",
            "R025",
            "R026",
            "R027",
            "R028",
        ],
        "Penyebab 1": [
            "P01",
            "P10",
            "P11",
            "P06",
            "P07",
            "P15",
            "P01",
            "P02",
            "P10",
            "P11",
            "P12",
            "P10",
            "P13",
            "P13",
            "P07",
            "P07",
            "P09",
            "P03",
            "P16",
            "P17",
            "P16",
            "P22",
            "P23",
            "P21",
            "P11",
            "P04",
            "P08",
            "P06",
        ],
        "Penyebab 2": [
            "P03",
            "",
            "",
            "P10",
            "P20",
            "",
            "P09",
            "P05",
            "",
            "",
            "",
            "",
            "P14",
            "",
            "P20",
            "",
            "",
            "",
            "P17",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
        ],
        "Penyebab 3": [
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "P18",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
        ],
        "Gangguan": [
            "G01",
            "G01",
            "G01",
            "G02",
            "G02",
            "G02",
            "G03",
            "G03",
            "G04",
            "G04",
            "G05",
            "G05",
            "G06",
            "G06",
            "G07",
            "G07",
            "G08",
            "G08",
            "G09",
            "G09",
            "G09",
            "G09",
            "G09",
            "G09",
            "G10",
            "G10",
            "G01",
            "G01",
        ],
        "CF Rule": [
            0.85,
            0.9,
            0.8,
            0.9,
            0.85,
            0.75,
            0.88,
            0.82,
            0.85,
            0.8,
            0.9,
            0.75,
            0.92,
            0.85,
            0.95,
            0.88,
            0.87,
            0.75,
            0.93,
            0.9,
            0.88,
            0.87,
            0.85,
            0.82,
            0.9,
            0.8,
            0.65,
            0.88,
        ],
        "Deskripsi": [
            "Jarak jauh + channel penuh -> WiFi lambat",
            "ISP problem -> WiFi lambat",
            "User terlalu banyak -> WiFi lambat",
            "Kabel rusak + ISP problem -> Putus koneksi",
            "Overheating + thermal throttling -> Putus koneksi",
            "Driver klien problem -> Putus koneksi",
            "Jarak jauh + interferensi -> Sinyal lemah",
            "Antena rusak + daya rendah -> Sinyal lemah",
            "ISP problem -> Latensi tinggi",
            "User terlalu banyak -> Latensi tinggi",
            "DNS server bermasalah -> DNS resolution issue",
            "ISP problem -> DNS issue",
            "DHCP rusak + IP range penuh -> DHCP problem",
            "DHCP server bermasalah -> DHCP problem",
            "Overheating + thermal throttling + RAM penuh -> AP overheat",
            "AP overheating -> AP problem",
            "Interferensi 2.4GHz -> Interferensi",
            "Channel tidak optimal -> Interferensi",
            "MAC filtering + password salah -> Auth fail",
            "Password salah -> Authentication failure",
            "MAC filtering blokir device -> Authentication failure",
            "Encryption mismatch -> Authentication failure",
            "Hidden SSID issue -> Cannot connect",
            "MAC collision/spoofing -> Authentication failure",
            "User terlalu banyak -> Congestion",
            "Bandwidth settings tidak optimal -> Congestion",
            "Firmware outdated -> WiFi lambat",
            "Kabel Ethernet rusak -> WiFi lambat",
        ],
    }
)

# ============================================================================
# SHEET 4: SYMPTOM MAPPING
# ============================================================================
symptom_df = pd.DataFrame(
    {
        "Symptom ID": [
            "slow_connection",
            "frequent_disconnect",
            "weak_signal",
            "high_latency",
            "dns_issue",
            "cannot_connect",
            "auth_failure_intermittent",
            "mac_blocking_detected",
            "encryption_mismatch",
            "ip_assignment_fail",
            "ap_hot",
            "many_devices",
            "intermittent_issue",
        ],
        "Gejala Klien": [
            "WiFi lambat",
            "WiFi sering putus",
            "Sinyal lemah",
            "Ping/delay tinggi",
            "DNS lookup lambat",
            "Device tidak bisa konek",
            "Autentikasi gagal kadang berhasil kadang tidak",
            "Device MAC terdeteksi tapi terblokir",
            "Enkripsi WiFi tidak sesuai dengan device",
            "Device dapat IP invalid",
            "AP panas",
            "Banyak device terhubung",
            "Gangguan intermittent",
        ],
        "Penyebab Utama": [
            "P01",
            "P06",
            "P01",
            "P10",
            "P12",
            "P17",
            "P16",
            "P16",
            "P22",
            "P13",
            "P07",
            "P11",
            "P06",
        ],
        "CF1": [0.7, 0.85, 0.85, 0.85, 0.9, 0.9, 0.8, 0.95, 0.9, 0.9, 0.95, 0.9, 0.7],
        "Penyebab 2": [
            "P10",
            "P10",
            "P02",
            "P11",
            "P10",
            "P16",
            "P21",
            "P21",
            "P17",
            "P14",
            "P20",
            "P04",
            "P09",
        ],
        "CF2": [0.85, 0.75, 0.8, 0.8, 0.75, 0.85, 0.75, 0.7, 0.6, 0.85, 0.9, 0.7, 0.75],
        "Penyebab 3": [
            "P11",
            "P07",
            "P05",
            "P04",
            "",
            "P22",
            "P22",
            "",
            "",
            "",
            "P18",
            "",
            "P15",
        ],
        "CF3": [0.8, 0.8, 0.7, 0.65, 0.0, 0.8, 0.7, 0.0, 0.0, 0.0, 0.7, 0.0, 0.8],
        "Penyebab 4": [
            "P03",
            "P15",
            "P09",
            "",
            "",
            "P23",
            "",
            "",
            "",
            "",
            "",
            "",
            "P08",
        ],
        "CF4": [0.6, 0.7, 0.75, 0.0, 0.0, 0.75, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.6],
    }
)

# ============================================================================
# SHEET 5: CF REFERENCE
# ============================================================================
cf_ref_df = pd.DataFrame(
    {
        "Item": [
            "CF Combination Formula",
            "Example CF₁ = 0.8, CF₂ = 0.6",
            "Result: CF_combined = 0.92",
            "",
            "Confidence Level: CF ≥ 0.8",
            "Confidence Level: CF 0.6 - 0.8",
            "Confidence Level: CF 0.4 - 0.6",
            "Confidence Level: CF < 0.4",
            "",
            "Technician Visit: CF > 0.8 or High Severity + CF > 0.7",
            "Technician Visit: Multiple Disturbances",
            "Technician Visit: High Severity, CF > 0.7",
            "Technician Visit: Medium Confidence (CF > 0.5)",
            "Technician Visit: CF < 0.5",
        ],
        "Description": [
            "CF_combined = CF₁ + CF₂(1 - CF₁)",
            "CF_combined = 0.8 + 0.6(1 - 0.8) = 0.8 + 0.12 = 0.92",
            "Final combined certainty factor",
            "",
            "Sangat Tinggi",
            "Tinggi",
            "Sedang",
            "Rendah",
            "",
            "SANGAT DIREKOMENDASIKAN",
            "SANGAT DIREKOMENDASIKAN",
            "DIREKOMENDASIKAN",
            "PERTIMBANGKAN",
            "TIDAK PERLU (coba troubleshoot manual)",
        ],
    }
)

# ============================================================================
# SHEET 6: DOCUMENTATION
# ============================================================================
doc_df = pd.DataFrame(
    {
        "Section": [
            "TUJUAN SISTEM",
            "TUJUAN SISTEM",
            "TUJUAN SISTEM",
            "TUJUAN SISTEM",
            "",
            "METODOLOGI",
            "METODOLOGI",
            "METODOLOGI",
            "METODOLOGI",
            "",
            "KOMPONEN SISTEM",
            "KOMPONEN SISTEM",
            "KOMPONEN SISTEM",
            "KOMPONEN SISTEM",
            "KOMPONEN SISTEM",
            "",
            "CARA KERJA",
            "CARA KERJA",
            "CARA KERJA",
            "CARA KERJA",
            "CARA KERJA",
            "CARA KERJA",
            "CARA KERJA",
            "",
            "FITUR UTAMA",
            "FITUR UTAMA",
            "FITUR UTAMA",
            "FITUR UTAMA",
            "FITUR UTAMA",
        ],
        "Content": [
            "Membuat sistem pelaporan gangguan WiFi dari client ke provider",
            "Mendiagnosa gangguan WiFi secara otomatis",
            "Menemukan root cause penyebab gangguan",
            "Menentukan apakah teknisi perlu berkunjung ke lokasi",
            "",
            "Rule-Based Expert System",
            "Forward Chaining Inference Engine",
            "Certainty Factor (CF) Reasoning",
            "Multi-evidence CF Combination",
            "",
            "1. Gangguan (G01-G10): 10 kategori gangguan WiFi utama",
            "2. Penyebab (P01-P20): 20 jenis penyebab gangguan",
            "3. Rules (R001-R024): 24 rules yang menghubungkan penyebab ke gangguan",
            "4. Symptom Mapping: Pemetaan gejala klien ke penyebab",
            "5. CF Reference: Rumus dan threshold untuk decision making",
            "",
            "1. Klien melaporkan gejala yang dialami",
            "2. Sistem memetakan gejala ke penyebab potensial dengan CF values",
            "3. Forward chaining engine mengaplikasikan rules untuk diagnosis",
            "4. CF values dikombinasikan menggunakan formula CF = CF₁ + CF₂(1 - CF₁)",
            "5. Sistem menghasilkan diagnosis dengan confidence level",
            "6. Sistem merekomendasikan apakah perlu kunjungan teknisi",
            "7. Generate report untuk dokumentasi",
            "",
            "Automatic diagnosis tanpa manual intervention",
            "Dokumentasi lengkap untuk setiap kasus",
            "Real-time recommendation untuk technician visit",
            "Scalable untuk penambahan rules dan causes baru",
            "Support untuk analisis historical data dan pattern recognition",
        ],
    }
)

# ============================================================================
# Save all sheets to Excel
# ============================================================================
try:
    # Try with openpyxl first
    with pd.ExcelWriter(output_file, engine="openpyxl") as writer:
        gangguan_df.to_excel(writer, sheet_name="Gangguan", index=False)
        penyebab_df.to_excel(writer, sheet_name="Penyebab", index=False)
        rules_df.to_excel(writer, sheet_name="Rules", index=False)
        symptom_df.to_excel(writer, sheet_name="Symptom Mapping", index=False)
        cf_ref_df.to_excel(writer, sheet_name="CF Reference", index=False)
        doc_df.to_excel(writer, sheet_name="Documentation", index=False)
except:
    # Fall back to xlsxwriter
    with pd.ExcelWriter(output_file, engine="xlsxwriter") as writer:
        gangguan_df.to_excel(writer, sheet_name="Gangguan", index=False)
        penyebab_df.to_excel(writer, sheet_name="Penyebab", index=False)
        rules_df.to_excel(writer, sheet_name="Rules", index=False)
        symptom_df.to_excel(writer, sheet_name="Symptom Mapping", index=False)
        cf_ref_df.to_excel(writer, sheet_name="CF Reference", index=False)
        doc_df.to_excel(writer, sheet_name="Documentation", index=False)

print(f"✓ Excel file created: {output_file}")
print(f"  Sheets created:")
print(f"  1. Gangguan - 10 categories of WiFi disturbances")
print(f"  2. Penyebab - 20 types of causes")
print(f"  3. Rules - 24 inference rules")
print(f"  4. Symptom Mapping - Mapping gejala klien")
print(f"  5. CF Reference - CF calculation reference")
print(f"  6. Documentation - System documentation")
